### ISSUE TITLE
Unable to run docker inside the container

### ISSUE THREAD

**Issue by amalsgit** [ninech/jnlp-slave-with-docker#3]
I created an ECS slave template with the options as shown in the image.

![image](https://user-images.githubusercontent.com/22020329/40538884-9fe55a5a-6030-11e8-9f67-ffa890cbc7b5.png)

Now when i run a Jenkins pipeline job as shown below:
```
node('jnlp-slave-docker'){
    sh "java -version"
    sh "docker info"
}
```

I am getting this error:  `Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?`
Can you please help me on how to fix this issue?

**Comment by neckhair** [comment]
@amalsgit Sorry, but we don't use and maintain this anymore. But I think you're using it wrong. As far as I can remember you have to start this image separately as a task on ECS and connect it as a Jenkins slave.
The problem in your case is that you don't have the Docker socket inside the image. In the Readme of this repo we tell you how to mount it as a volume.
